[[books]]
title = "\"Crash\""
[[books]]
title = "\""
[[books]]
title = "A Skeptic's Guide to the Future"
[[books]]
genre = "Experimental"
author = "Unknown"
title = "Untitled"
[[books]]
title = "Space Battle Lunchtime"

[[hbooks]]
title = "Snow Crash"
